FROM nvidia/cuda:11.8.0-base-ubuntu22.04

RUN apt-get update && apt-get install -y build-essential
RUN apt-get install python3.9 -y
RUN apt-get install python3-pip -y

RUN python3 -m pip install --no-cache-dir --upgrade pip \
  && python3 -m pip install --no-cache-dir torch transformers fastapi uvicorn

WORKDIR /workspace
COPY models/xlm-roberta-base-language-detection models/xlm-roberta-base-language-detection
COPY api-cuda.py api.py

ENTRYPOINT ["uvicorn", "api:app", "--host", "0.0.0.0"]
